#!/bin/sh

# Delete old files

source "$( cd "$( dirname "$0" )" && pwd )/common"

go_to_laravel_dir

color "Deleting obsolete files in `pwd`" red
color "Press ENTER to continue or CONTROL+C to cancel" yellow
read

# Editor backps
find . -type f \( -name ".*~" -o -name "*~" \) -exec rm {} \;

# Git conflicts remains
find . -type f \( -name "*.php.orig" -o -name "*.php.BACKUP.*.php" -o -name "*.php.BASE.*.php" -o  -name "*.php.LOCAL.*.php" -o -name "*.php.REMOTE.*.php" \) -exec rm -i {} \;

exit 0

