#!/bin/sh

# Search code for pending tasks

source "$( cd "$( dirname "$0" )" && pwd )/common" || exit 1

go_to_laravel_dir

color "Pending tasks"

grep -Ir --colour=auto \
--exclude-from=.gitignore  \
--exclude="`basename $0`"  \
--exclude="manual.html" \
--exclude-dir="\.git"  \
--exclude-dir="storage"  \
--exclude-dir="vendor"  \
"to-do" .

exit $?
